// Piano keys 88 notes as reference
// Order of prominance:
// lowercase by frequency
// uppercase by frequency
// punctuation by frequency
// numbers 0-9
// arbitrary symbols used in English (order and choices subjective)

const CODE = {
  // Lowercase
  'e' : { note: 'C4', hand: 'right' },
  't' : { note: 'D4', hand: 'right' },
  'a' : { note: 'B3', hand: 'left' },
  'o' : { note: 'E4', hand: 'right' },
  'i' : { note: 'A3', hand: 'left' },
  'n' : { note: 'F4', hand: 'right' },
  's' : { note: 'G3', hand: 'left' },
  'h' : { note: 'G4', hand: 'right' },
  'r' : { note: 'F3', hand: 'left' },
  'd' : { note: 'A4', hand: 'right' },
  'l' : { note: 'E3', hand: 'left' },
  'c' : { note: 'B4', hand: 'right' },
  'u' : { note: 'D3', hand: 'left' },
  'm' : { note: 'C5', hand: 'right' },
  'w' : { note: 'C3', hand: 'left' },
  'f' : { note: 'D5', hand: 'right' },
  'g' : { note: 'B2', hand: 'left' },
  'y' : { note: 'E5', hand: 'right' },
  'p' : { note: 'A2', hand: 'left' },
  'b' : { note: 'F5', hand: 'right' },
  'v' : { note: 'G2', hand: 'left' },
  'k' : { note: 'G5', hand: 'right' },
  'j' : { note: 'F2', hand: 'left' },
  'x' : { note: 'A5', hand: 'right' },
  'q' : { note: 'E2', hand: 'left' },
  'z' : { note: 'B5', hand: 'right' },
  // uppercase
  'T' : { note: 'D2',  hand: 'left' },
  'A' : { note: 'C#4', hand: 'right' },
  'S' : { note: 'C2',  hand: 'left' },
  'H' : { note: 'D#4', hand: 'right' },
  'W' : { note: 'Bb3', hand: 'left' },
  'I' : { note: 'F#4', hand: 'right' },
  'O' : { note: 'Ab3', hand: 'left' },
  'B' : { note: 'G#4', hand: 'right' },
  'M' : { note: 'Gb3', hand: 'left' },
  'F' : { note: 'A#4', hand: 'right' },
  'C' : { note: 'Eb3', hand: 'left' },
  'L' : { note: 'C#5', hand: 'right' },
  'D' : { note: 'Db3', hand: 'left' },
  'P' : { note: 'D#5', hand: 'right' },
  'N' : { note: 'Bb2', hand: 'left' },
  'E' : { note: 'F#5', hand: 'right' },
  'G' : { note: 'Ab2', hand: 'left' },
  'R' : { note: 'G#5', hand: 'right' },
  'Y' : { note: 'Gb2', hand: 'left' },
  'U' : { note: 'A#5', hand: 'right' },
  'V' : { note: 'Eb2', hand: 'left' },
  'J' : { note: 'C6',  hand: 'right' },
  'K' : { note: 'Db2', hand: 'left' },
  'Q' : { note: 'D6',  hand: 'right' },
  'Z' : { note: 'F6',  hand: 'right' },
  'X' : { note: 'E6',  hand: 'right' },
  // punctuation
  '.'  : { note: 'G6', hand: 'right' },
  ','  : { note: 'B1', hand: 'left' },
  ';'  : { note: 'A6', hand: 'right' },
  ':'  : { note: 'A1', hand: 'left' },
  '!'  : { note: 'B6', hand: 'right' },
  '?'  : { note: 'G1', hand: 'left' },
  "'"  : { note: 'C7', hand: 'right' },
  '"'  : { note: 'F1', hand: 'left' },
  // numbers
  '0' : { note: 'D7', hand: 'right' },
  '1' : { note: 'E1', hand: 'left' },
  '2' : { note: 'E7', hand: 'right' },
  '3' : { note: 'D1', hand: 'left' },
  '4' : { note: 'F7', hand: 'right' },
  '5' : { note: 'C1', hand: 'left' },
  '6' : { note: 'G7', hand: 'right' },
  '7' : { note: 'B0', hand: 'left' },
  '8' : { note: 'A7', hand: 'right' },
  '9' : { note: 'A0', hand: 'left' },
  // symbols
  '(' : { note: 'B7',  hand: 'right' },
  ')' : { note: 'Bb1', hand: 'left' },
  '[' : { note: 'C8',  hand: 'right' },
  ']' : { note: 'Ab1', hand: 'left' },
  '{' : { note: 'C#6', hand: 'right' },
  '}' : { note: 'Gb1', hand: 'left' },
  '$' : { note: 'D#6', hand: 'right' },
  '&' : { note: 'Eb1', hand: 'left' },
  '#' : { note: 'F#6', hand: 'right' },
  '%' : { note: 'Db1', hand: 'left' },
  '*' : { note: 'G#6', hand: 'right' },
  '=' : { note: 'Bb0', hand: 'left' },
  '+' : { note: 'A#6', hand: 'right' },
  '_' : { note: 'D#7', hand: 'right' },
  '^' : { note: 'F#7', hand: 'right' },
  '~' : { note: 'G#7', hand: 'right' },
  '@' : { note: 'C#7', hand: 'right' },
  '`' : { note: 'A#7', hand: 'right' }
}

export { CODE }
